# Generated by Django 3.1.4 on 2021-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_auto_20210721_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
