# Generated by Django 3.1.4 on 2021-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210714_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_authentication',
            name='phonenumber',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
